# UAM Simulator Configuration
# component_schema.py structure has to respect this config.yaml

# new types can be added here
# provide a class/name for uav, and its attrs as described


#### CONFIG ####
simulator:
  dt: 0.5
  total_timestep: 10000
  mode: '2D' # or 3D - used for rendering and dynamics, controller and sensor check
  seed: 123456

vertiport:
  number_of_landing_pad: 3

airspace:
  location_name: 'Austin, Texas, USA'
  number_of_vertiports: 11
  vertiport_tag_list: [['building', 'commercial']]
  airspace_restricted_area_tag_list: [['building', 'office']]



# this whole section needs to communicate with AER_BUS and ATC
# LEARNING is the only reserved type_name - strictly for UAV using RL controller during training phase
fleet_composition:
  - type_name: STANDARD
    count: 2 # ATC handles id and type_name for dynamics, controller, and state update
    dynamics: PointMass
    controller: PIDPointMassController
    sensor: PartialSensor # OR GlobalSensor
    planner: PointMass-PID 
 
  - type_name: HEAVY
    count: 3 # ATC handles id and type_name for dynamics, controller, and state update
    dynamics: PointMass
    controller: PIDPointMassController
    sensor: PartialSensor # OR GlobalSensor
    planner: PointMass-PID 
   


#### CONFIG ####
