from typing import Any, Dict, List, Optional, Tuple

import numpy as np


class DemandModelMixin:
    """
    Opt-in OD-demand simulation behavior for SimulatorManager.

    Ported from the former simulator_manager_vp_design.py. All methods here
    read/write self.lambda_matrix / self.vertiport_region_map /
    self.zone_region_map / self.n_regions / self._demand_rng, which
    SimulatorManager's __init__ sets (defaulting to demand-mode off when no
    lambda_matrix is supplied), plus self.airspace / self.atc / self._state /
    self.dt / self.config already owned by SimulatorManager itself.

    When self.lambda_matrix is None, none of these methods are invoked by
    SimulatorManager.reset()/step() — the default mission-sim path is
    untouched.
    """

    def _init_demand_state(self):
        """Initialise per-episode demand tracking structures.
        Called by reset() at the start of every episode (only when
        self.lambda_matrix is not None).

        Structures initialised:
          departure_queues    — one FIFO list per vertiport; each entry is a
                               (dest_vertiport_id, enqueue_step) tuple.
          _trip_log           — list of dicts, one per COMPLETED trip.
          _demand_gen_od      — (N, N) int array counting trips GENERATED this
                               episode per OD region pair. Denominator of B3.
          _trips_completed_od — (N, N) int array counting trips COMPLETED.
          _pads_occupied_sum  — (n_vp,) float; running sum of pads_occupied.
          _queue_length_sum   — (n_vp,) float; running sum of uavs_waiting.
          _uavs_in_flight_sum — int; running sum of in-flight count → B6.
        Step count uses self._state.currentstep (set by step()).
        """
        n_vp = len(self.airspace.vertiport_list)

        # Departure queues: vertiport_id → list of (dest_vp_id, enqueue_step)
        # Trips generated by the Poisson process are pushed here and popped
        # when a UAV becomes available for a mission.
        self.departure_queues: Dict[int, List[Tuple[int, int]]] = {
            vp.id: [] for vp in self.airspace.vertiport_list
        }

        # Trip completion log: one dict per completed trip.
        self._trip_log: List[Dict] = []

        # OD trip counters at region level (N×N).
        if self.n_regions > 0:
            self._demand_gen_od = np.zeros((self.n_regions, self.n_regions), dtype=int)
            self._trips_completed_od = np.zeros((self.n_regions, self.n_regions), dtype=int)
        else:
            self._demand_gen_od = np.zeros((0, 0), dtype=int)
            self._trips_completed_od = np.zeros((0, 0), dtype=int)

        # Step-level accumulators for time-averaged node features (B4, B5, B6).
        self._vp_index_to_id: List[int] = [vp.id for vp in self.airspace.vertiport_list]
        self._vp_id_to_vp: Dict[int, Any] = {vp.id: vp for vp in self.airspace.vertiport_list}
        self._pads_occupied_sum = np.zeros(n_vp, dtype=float)
        self._queue_length_sum = np.zeros(n_vp, dtype=float)
        self._uavs_in_flight_sum = 0

        # Invalidate the cached region→vertiport inverse; _generate_demand
        # rebuilds it lazily on first use each episode.
        self._region_to_vp: Optional[Dict[int, int]] = None

    def _generate_demand(self):
        """Poisson trip generation — runs once per step.
        Pushes trip requests into vertiport departure queues.

        For each OD region pair (i, j) with i != j:
          p_ij = lambda_matrix[i,j] * dt / 60   (Bernoulli probability)
          Draw u ~ U(0,1); if u < p_ij: push a trip request into the departure
          queue at the vertiport serving region i.
        """
        if not self._region_to_vp:
            self._region_to_vp = {
                region: vp_id for vp_id, region in self.vertiport_region_map.items()
            }

        dt_min = self.dt / 60.0  # convert simulator dt (seconds) to minutes

        for i in range(self.n_regions):
            origin_vp_id = self._region_to_vp.get(i)
            if origin_vp_id is None:
                continue  # region i has no selected vertiport this episode

            for j in range(self.n_regions):
                if i == j:
                    continue  # no intra-region demand (Level 1 rule)

                dest_vp_id = self._region_to_vp.get(j)
                if dest_vp_id is None:
                    continue

                rate = self.lambda_matrix[i, j]  # trips/min
                if rate <= 0.0:
                    continue

                p_ij = rate * dt_min
                u = self._demand_rng.random()
                if u < p_ij:
                    self.departure_queues[origin_vp_id].append(
                        (dest_vp_id, self._state.currentstep)
                    )
                    self._demand_gen_od[i, j] += 1

    def _dispatch_mission(self, uav_id: int, origin_vp_id: int, dest_vp_id: int, enqueue_step: int):
        """Assign a queued demand trip to an idle UAV and open a trip log entry."""
        o_region = self.vertiport_region_map.get(origin_vp_id, -1)
        d_region = self.vertiport_region_map.get(dest_vp_id, -1)

        # Uses assign_start_end directly (mirrors reassign_new_mission but
        # with specific vertiports instead of random selection). Must NOT use
        # assign_mission_start_end_vertiport: that appends to uav_id_list, but
        # the UAV is already in origin_vp.uav_id_list from landing_procedure.
        _uav = self.atc.uav_dict[uav_id]
        assert _uav.end_vertiport == self._vp_id_to_vp[origin_vp_id]
        _uav.assign_start_end(
            self._vp_id_to_vp[origin_vp_id],
            self._vp_id_to_vp[dest_vp_id],
            self.atc.airspace_mid_point_coord,
        )

        self._trip_log.append({
            'uav_id': uav_id,
            'o_region': o_region,
            'd_region': d_region,
            'origin_vp_id': origin_vp_id,
            'dest_vp_id': dest_vp_id,
            'enqueue_step': enqueue_step,
            'depart_step': self._state.currentstep,
            'arrive_airspace_step': None,  # filled by _log_arrive_airspace
            'land_step': None,  # filled by _log_land
        })

    def _log_arrive_airspace(self, uav_id: int):
        """Log the step at which uav_id entered the landing queue (no-op if not queued)."""
        uav = self.atc.uav_dict.get(uav_id)
        if uav is None:
            return
        for vertiport in self.airspace.vertiport_list:
            if uav_id in vertiport.landing_queue:
                for entry in reversed(self._trip_log):
                    if entry['uav_id'] == uav_id and entry['arrive_airspace_step'] is None:
                        entry['arrive_airspace_step'] = self._state.currentstep
                break

    def _log_land(self, uav_id: int, vertiport_id: int):
        """Record completed landing and increment OD counters."""
        for entry in reversed(self._trip_log):
            if entry['uav_id'] == uav_id and entry['land_step'] is None:
                entry['land_step'] = self._state.currentstep
                if entry['arrive_airspace_step'] is None:
                    entry['arrive_airspace_step'] = self._state.currentstep
                o = entry['o_region']
                d = entry['d_region']
                if 0 <= o < self.n_regions and 0 <= d < self.n_regions:
                    self._trips_completed_od[o, d] += 1
                break

    def _accumulate_step_metrics(self):
        """Accumulate step-level values for time-averaged metrics B4/B5/B6."""
        for k, vp_id in enumerate(self._vp_index_to_id):
            vertiport = self._vp_id_to_vp.get(vp_id)
            if vertiport is None:
                continue
            self._pads_occupied_sum[k] += len(vertiport.uav_id_list)
            self._queue_length_sum[k] += len(vertiport.get_landing_queue())

        in_flight = sum(
            1 for uav in self.atc.uav_dict.values() if getattr(uav, 'uav_in_flight', False)
        )
        self._uavs_in_flight_sum += in_flight

    def get_episode_metrics(self) -> Dict:
        """Aggregate all step-level logs into Group B observation features for the RL env.

        Returns a dict with keys: pair_avg_trip_time, pair_avg_wait_time,
        pair_demand_served_ratio, demand_generated_od, trips_completed_od,
        utilization, queue_length, fleet_utilization, demand_served_ratio,
        vp_index_to_id.
        """
        N = self.n_regions
        T = max(self._state.currentstep, 1)  # guard against division by zero

        trip_time_sum = np.zeros((N, N), dtype=float)
        wait_time_sum = np.zeros((N, N), dtype=float)
        completed_count = np.zeros((N, N), dtype=int)

        for entry in self._trip_log:
            o, d = entry['o_region'], entry['d_region']
            if not (0 <= o < N and 0 <= d < N):
                continue
            if entry['land_step'] is None:
                continue  # trip not completed — skip (counts as unserved)

            trip_steps = entry['land_step'] - entry['depart_step']
            wait_steps = entry['land_step'] - entry['arrive_airspace_step']

            trip_time_sum[o, d] += trip_steps * self.dt
            wait_time_sum[o, d] += wait_steps * self.dt
            completed_count[o, d] += 1

        pair_avg_trip_time = np.where(
            completed_count > 0, trip_time_sum / np.maximum(completed_count, 1), 0.0
        )
        pair_avg_wait_time = np.where(
            completed_count > 0, wait_time_sum / np.maximum(completed_count, 1), 0.0
        )
        pair_demand_served_ratio = np.where(
            self._demand_gen_od > 0,
            self._trips_completed_od / np.maximum(self._demand_gen_od, 1),
            1.0,
        )

        pad_capacity = getattr(self.config.airspace, 'pad_capacity', 1)
        utilization = self._pads_occupied_sum / (T * max(pad_capacity, 1))
        utilization = np.clip(utilization, 0.0, 1.0)

        queue_length = self._queue_length_sum / T

        total_uavs = max(len(self.atc.uav_dict), 1)
        fleet_utilization = self._uavs_in_flight_sum / (T * total_uavs)
        fleet_utilization = float(np.clip(fleet_utilization, 0.0, 1.0))

        total_generated = int(self._demand_gen_od.sum())
        total_completed = int(self._trips_completed_od.sum())
        demand_served_ratio = total_completed / total_generated if total_generated > 0 else 1.0

        return {
            'pair_avg_trip_time': pair_avg_trip_time,
            'pair_avg_wait_time': pair_avg_wait_time,
            'pair_demand_served_ratio': pair_demand_served_ratio,
            'demand_generated_od': self._demand_gen_od.copy(),
            'trips_completed_od': self._trips_completed_od.copy(),
            'utilization': utilization,
            'queue_length': queue_length,
            'fleet_utilization': fleet_utilization,
            'demand_served_ratio': demand_served_ratio,
            'vp_index_to_id': list(self._vp_index_to_id),
        }

    def update_vertiport_region_map(self, vertiport_region_map: Dict[int, int]):
        """Update the vertiport→region mapping for the next episode. Call before reset()."""
        self.vertiport_region_map = vertiport_region_map
        self._region_to_vp = None
